### ISSUE TITLE
Разделить методы для HasDataProvider 

### ISSUE THREAD

**Issue by Znack** [fullstack-development/servant-rest-entities#11]
Оставить в текущем тайпклассе только методы
unpack
pack
getPK
getID
prepareToCreate

Все остальные разделить по максимуму на отдельные тайпклассы, чтобы можно было для отдельных сущностей по разному поддерживаемые методы настраивать

**Comment by mrRomanovsky** [comment]
У нас сейчас все эти методы в HasDataProvider - их надо спустить в DataProvider?

**Comment by Znack** [comment]
Не-не, ты это не сможешь сделать, DataProvider у нас создается для типов провайдеров, например для базы данных постгрес, или для локального кеша. А HasDataProvider для каждой сущности. Спустить ты тут чисто семантически не сможешь :)

Тут надо кучу других тайпклассов наделать, лучше в отдельных подмодулях. И DataProvider тоже в сабмодуль вынести

**Comment by mrRomanovsky** [comment]
Ну просто ишью называется "разделить методы для DataProvider", а методы эти все из HasDataProvider - я и подумал, может там что-то внезапное :)

**Comment by mrRomanovsky** [comment]
В общем, они так и должны быть в HasDataProvider, просто всё лишнее оттуда вытащить, да?

**Comment by Znack** [comment]
С именем ишью мой косяк :) надо разделить все из HasDataProvider :)

получается, что в HasDataProvider надо все методы убрать кроме списка, который я в описании сделал :) Убрать это надо в отдельные тайпклассы, создавая для каждой функциональности по отдельному тайпклассу (для загрузки сущности, для сохранения в базу, для фильтрации и тд). Таким образом мы можем разные сущности наделять разным функционалом просто добавляя ему инстансы тайпклассов

**Comment by Znack** [comment]
Сделано в рамках #12
