### ISSUE TITLE
Перейти от DataFamily в сериализаторах к Injective TypeFamily

### ISSUE THREAD

**Issue by Znack** [fullstack-development/servant-rest-entities#13]
Не срочная таска, просто чтобы сделать код немного приятней. Мы в свое время прикрепляли сериализаторы к инстансам обработчиков через  data family из-за их инжективности, сейчас это можно сделать и посредством аналога fundep для type family — тогда лучше на него и перейти

**Comment by mrRomanovsky** [comment]
Я там вижу просто MultiParamTypeClasses + fundeps: https://github.com/fullstack-development/servant-rest-entities/blob/acdfed96c9e24cd6226a84de67ec09a92a9de7e6/src/RestEntities/Serializables.hs#L10. А где DataFamily?

**Comment by Znack** [comment]
Вот тут лучше смотреть :)
https://github.com/fullstack-development/servant-rest-entities/blob/acdfed96c9e24cd6226a84de67ec09a92a9de7e6/src/RestEntities/WebActions/Create.hs#L26-L27
У нас в самих эндпоинтах дата фэмили уже

**Comment by mrRomanovsky** [comment]
https://github.com/fullstack-development/servant-rest-entities/pull/12/commits/bdbdc22c8fa4a31fde96d965df2d7d2c31ddd5fd

**Comment by Znack** [comment]
Сделано в рамках #12
